import os
import ujson
from jinja2 import Environment

from pydantic_settings import BaseSettings, SettingsConfigDict


class _settings(BaseSettings):
    APP_VERSION: str = ""
    ROOT_PATH: str = os.path.abspath("")

    USERNAME: str = ""
    PASSWORD: str = ""
    EMAIL: str = ""
    APP_DEBUG: bool = False
    # JWT
    SECRET_KEY: str = ""
    ALGORITHM: str = ""
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 30

    # Oauth2.0
    GOOGLE_CLIENT_ID: str = ""
    GOOGLE_CLIENT_SECRET: str = ""
    FACEBOOK_CLIENT_ID: str = ""
    FACEBOOK_CLIENT_SECRET: str = ""
    APPLE_CLIENT_ID: str = ""
    APPLE_CLIENT_SECRET: str = ""

    OAUTH_PROVIDERS: list = ["google", "facebook", "apple"]

    model_config = SettingsConfigDict(
        env_file=".env", env_file_encoding="utf-8", extra="ignore"
    )

    # mysql
    DB_HOST: str = ""
    DB_PORT: int = 5432
    MYSQL_DB_NAME: str = ""
    MYSQL_DB_USER: str = ""
    MYSQL_DB_PASSWORD: str = ""


settings = _settings()


class _ViteSettings(BaseSettings):
    VITE_DEV_MODE: bool = False

    VITE_DEV_SERVER_PROTOCOL: str = "http"

    VITE_DEV_SERVER_HOST: str = "localhost"

    VITE_DEV_SERVER_PORT: str = 5174

    VITE_DEV_SERVER_URL: str = (
        f"{VITE_DEV_SERVER_PROTOCOL}://{VITE_DEV_SERVER_HOST}:{VITE_DEV_SERVER_PORT}"
    )

    # Vite dev server path to hot module replacement.
    VITE_WS_CLIENT_PATH: str = "@vite/client"

    # Path to vite compiled assets (only used in production mode).
    VITE_ASSETS_PATH: str | None = None

    # Vite static asset url
    VITE_STATIC_URL: str | None = None

    # Path to your manifest file generated by Vite.
    VITE_MANIFEST_PATH: str = f"{settings.ROOT_PATH}/dist/manifest.json"

    model_config = SettingsConfigDict(
        env_file=".env", env_file_encoding="utf-8", extra="ignore"
    )


class _Vite:
    """Vite helping function for Jinja2"""

    def __init__(self):
        self.vite_settings = _ViteSettings()
        self._manifest = None

    def vite_hmr_client(self):
        return (
            self.__script_tag(
                src=f"{self.vite_settings.VITE_DEV_SERVER_URL}/{self.vite_settings.VITE_WS_CLIENT_PATH}",
                attrs={"type": "module"},
            )
            if self.vite_settings.VITE_DEV_MODE
            else ""
        )

    def vite_asset(self, asset_path: str):
        if self.vite_settings.VITE_DEV_MODE:
            return self.__script_tag(
                src=f"{self.vite_settings.VITE_DEV_SERVER_URL}/{asset_path}",
                attrs={"type": "module"},
            )

        asset_tags = []

        with open(self.vite_settings.VITE_MANIFEST_PATH) as file:
            # manifest_content = file.read()
            self._manifest = ujson.load(file)

        asset_tags.extend(self.__css_assets_handle(asset_path, []))

        file_path = self._manifest[asset_path]["file"]

        src = (
            f"{self.vite_settings.VITE_STATIC_URL}/{file_path}"
            if self.vite_settings.VITE_STATIC_URL
            else f"/{file_path}"
        )

        asset_tags.append(self.__script_tag(src=src, attrs={"type": "module"}))

        return "\n".join(asset_tags)

    def jinja2_env_import(self, env: Environment):
        imports = [
            {"name": "vite_hmr_client", "func": self.vite_hmr_client},
            {"name": "vite_asset", "func": self.vite_asset},
        ]

        for _import in imports:
            env.globals[_import["name"]] = _import["func"]

    def __css_assets_handle(self, asset_path: str, processed: list[str]):
        stylesheet_tags = []

        entrypoint = self._manifest[asset_path]

        for import_ in entrypoint.get("imports", []):
            stylesheet_tags.extend(self.__css_assets_handle(import_, processed))

        for css_path in entrypoint.get("css", []):
            if css_path not in processed:
                stylesheet_tags.append(self.__link_stylesheet_tag(css_path))

                processed.append(css_path)

        return stylesheet_tags

    def __script_tag(self, src: str, attrs: dict = None):
        attrs_str = (
            " ".join([f"{key}={value}" for key, value in attrs.items()])
            if attrs is not None
            else ""
        )

        return f'<script {attrs_str} src="{src}"></script>'

    def __link_stylesheet_tag(self, file_path: str):
        href = (
            f"{self.vite_settings.VITE_STATIC_URL}/{file_path}"
            if self.vite_settings.VITE_STATIC_URL
            else f"/{file_path}"
        )

        return f'<link rel="stylesheet" href="{href}" />'


vite = _Vite()
